'use strict';

const ELEMENTS = {
  风: { icon: '風', css: 'wind' },
  火: { icon: '火', css: 'fire' },
  水: { icon: '水', css: 'water' },
  土: { icon: '土', css: 'earth' },
  雷: { icon: '雷', css: 'lightning' },
  阴: { icon: '陰', css: 'yin' },
  体: { icon: '体', css: 'body' }
};

const NINJAS = [
  {id:'naruto', name:'漩涡鸣人', short:'鸣人', icon:'螺', power:78, mult:1.20, elements:['风'], teams:['第七班'], roles:['强攻'], tags:['人柱力','影分身','螺旋丸'], rarity:'rare'},
  {id:'sasuke', name:'宇智波佐助', short:'佐助', icon:'写', power:84, mult:1.25, elements:['火','雷'], teams:['第七班'], roles:['强攻'], tags:['宇智波','写轮眼','千鸟'], rarity:'rare'},
  {id:'sakura', name:'春野樱', short:'小樱', icon:'樱', power:58, mult:1.10, elements:['土'], teams:['第七班'], roles:['医疗','强攻'], tags:['怪力','医疗'], rarity:'common'},
  {id:'kakashi', name:'旗木卡卡西', short:'卡卡西', icon:'雷', power:75, mult:1.22, elements:['雷'], teams:['第七班'], roles:['战术','控制'], tags:['写轮眼','雷切'], rarity:'rare'},
  {id:'yamato', name:'大和', short:'大和', icon:'木', power:68, mult:1.16, elements:['土','水'], teams:['大和班'], roles:['控制','防守'], tags:['木遁'], rarity:'uncommon'},
  {id:'sai', name:'佐井', short:'佐井', icon:'墨', power:62, mult:1.12, elements:['阴'], teams:['大和班'], roles:['控制'], tags:['超兽伪画'], rarity:'common'},
  {id:'shikamaru', name:'奈良鹿丸', short:'鹿丸', icon:'影', power:54, mult:1.18, elements:['阴'], teams:['第十班'], roles:['战术','控制'], tags:['影缝'], rarity:'uncommon'},
  {id:'ino', name:'山中井野', short:'井野', icon:'心', power:48, mult:1.12, elements:['阴'], teams:['第十班'], roles:['医疗','控制'], tags:['心转身'], rarity:'common'},
  {id:'choji', name:'秋道丁次', short:'丁次', icon:'倍', power:74, mult:1.08, elements:['土'], teams:['第十班'], roles:['强攻','防守'], tags:['倍化'], rarity:'common'},
  {id:'asuma', name:'猿飞阿斯玛', short:'阿斯玛', icon:'刃', power:72, mult:1.16, elements:['风','火'], teams:['第十班'], roles:['强攻'], tags:['风刃'], rarity:'uncommon'},
  {id:'hinata', name:'日向雏田', short:'雏田', icon:'柔', power:59, mult:1.16, elements:['体'], teams:['第八班'], roles:['支援','强攻'], tags:['白眼','柔拳'], rarity:'uncommon'},
  {id:'kiba', name:'犬冢牙', short:'牙', icon:'牙', power:66, mult:1.10, elements:['风'], teams:['第八班'], roles:['强攻'], tags:['兽忍'], rarity:'common'},
  {id:'shino', name:'油女志乃', short:'志乃', icon:'虫', power:57, mult:1.14, elements:['土'], teams:['第八班'], roles:['控制'], tags:['寄坏虫'], rarity:'common'},
  {id:'kurenai', name:'夕日红', short:'红', icon:'幻', power:61, mult:1.18, elements:['阴'], teams:['第八班'], roles:['控制','战术'], tags:['幻术'], rarity:'uncommon'},
  {id:'gaara', name:'我爱罗', short:'我爱罗', icon:'砂', power:82, mult:1.22, elements:['土'], teams:['砂之三姐弟'], roles:['控制','防守'], tags:['人柱力','砂遁'], rarity:'rare'},
  {id:'temari', name:'手鞠', short:'手鞠', icon:'扇', power:73, mult:1.18, elements:['风'], teams:['砂之三姐弟'], roles:['强攻'], tags:['风遁'], rarity:'uncommon'},
  {id:'kankuro', name:'勘九郎', short:'勘九郎', icon:'傀', power:65, mult:1.14, elements:['土'], teams:['砂之三姐弟'], roles:['控制'], tags:['傀儡'], rarity:'common'},
  {id:'jiraiya', name:'自来也', short:'自来也', icon:'仙', power:96, mult:1.35, elements:['火','水'], teams:['传说三忍'], roles:['强攻','战术'], tags:['仙人','通灵','螺旋丸'], rarity:'epic'},
  {id:'tsunade', name:'纲手', short:'纲手', icon:'纲', power:92, mult:1.32, elements:['土'], teams:['传说三忍'], roles:['医疗','强攻'], tags:['怪力','医疗','百豪'], rarity:'epic'},
  {id:'orochimaru', name:'大蛇丸', short:'大蛇丸', icon:'蛇', power:90, mult:1.34, elements:['风','阴'], teams:['传说三忍'], roles:['控制','战术'], tags:['禁术','通灵'], rarity:'epic'},
  {id:'itachi', name:'宇智波鼬', short:'鼬', icon:'月', power:102, mult:1.42, elements:['火','阴'], teams:['晓'], roles:['控制','强攻'], tags:['宇智波','写轮眼','幻术'], rarity:'epic'},
  {id:'kisame', name:'干柿鬼鲛', short:'鬼鲛', icon:'鲛', power:94, mult:1.30, elements:['水'], teams:['晓'], roles:['强攻','防守'], tags:['鲛肌'], rarity:'rare'},
  {id:'deidara', name:'迪达拉', short:'迪达拉', icon:'爆', power:97, mult:1.32, elements:['土'], teams:['晓'], roles:['强攻'], tags:['爆遁'], rarity:'rare'},
  {id:'pain', name:'佩恩', short:'佩恩', icon:'輪', power:110, mult:1.48, elements:['雷','阴'], teams:['晓'], roles:['控制','强攻'], tags:['轮回眼'], rarity:'legendary'},
  {id:'minato', name:'波风水门', short:'水门', icon:'闪', power:108, mult:1.44, elements:['风','雷'], teams:['火影'], roles:['强攻','战术'], tags:['飞雷神','螺旋丸'], rarity:'legendary'},
  {id:'guy', name:'迈特凯', short:'凯', icon:'门', power:93, mult:1.30, elements:['体'], teams:['凯班'], roles:['强攻'], tags:['八门遁甲'], rarity:'rare'},
  {id:'lee', name:'洛克李', short:'小李', icon:'拳', power:76, mult:1.20, elements:['体'], teams:['凯班'], roles:['强攻'], tags:['八门遁甲'], rarity:'uncommon'},
  {id:'neji', name:'日向宁次', short:'宁次', icon:'穴', power:79, mult:1.22, elements:['体'], teams:['凯班'], roles:['控制','强攻'], tags:['白眼','柔拳'], rarity:'rare'},
  {id:'hashirama', name:'千手柱间', short:'柱间', icon:'森', power:126, mult:1.58, elements:['土','水'], teams:['火影'], roles:['强攻','控制'], tags:['木遁','仙人'], rarity:'legendary'},
  {id:'madara', name:'宇智波斑', short:'斑', icon:'焰', power:132, mult:1.62, elements:['火','阴'], teams:['传说'], roles:['强攻','控制'], tags:['宇智波','写轮眼'], rarity:'legendary'},
  {id:'obito', name:'宇智波带土', short:'带土', icon:'虚', power:112, mult:1.46, elements:['火','阴'], teams:['晓'], roles:['控制','战术'], tags:['宇智波','写轮眼','时空间'], rarity:'epic'},
{"id": "tenten", "name": "天天", "short": "天天", "icon": "天", "power": 70, "mult": 1.18, "elements": ["体"], "teams": ["凯班"], "roles": ["强攻", "支援"], "tags": ["忍具", "通灵"], "rarity": "uncommon"},
{"id": "tobirama", "name": "千手扉间", "short": "扉间", "icon": "扉", "power": 112, "mult": 1.45, "elements": ["水", "雷"], "teams": ["火影"], "roles": ["战术", "控制"], "tags": ["飞雷神", "水遁"], "rarity": "legendary"},
{"id": "hiruzen", "name": "猿飞日斩", "short": "日斩", "icon": "日", "power": 98, "mult": 1.34, "elements": ["火", "土"], "teams": ["火影"], "roles": ["战术", "强攻"], "tags": ["通灵", "忍具"], "rarity": "epic"},
{"id": "kushina", "name": "漩涡玖辛奈", "short": "玖辛奈", "icon": "玖", "power": 87, "mult": 1.32, "elements": ["水", "阴"], "teams": ["漩涡家族"], "roles": ["控制", "支援"], "tags": ["封印", "人柱力"], "rarity": "epic"},
{"id": "konan", "name": "小南", "short": "小南", "icon": "小", "power": 90, "mult": 1.3, "elements": ["风", "阴"], "teams": ["晓"], "roles": ["控制", "支援"], "tags": ["纸遁"], "rarity": "rare"},
{"id": "sasori", "name": "赤砂之蝎", "short": "蝎", "icon": "蝎", "power": 95, "mult": 1.34, "elements": ["土", "阴"], "teams": ["晓"], "roles": ["控制", "战术"], "tags": ["傀儡", "忍具"], "rarity": "epic"},
{"id": "hidan", "name": "飞段", "short": "飞段", "icon": "飞", "power": 91, "mult": 1.28, "elements": ["体", "阴"], "teams": ["晓"], "roles": ["强攻"], "tags": ["禁术", "忍具"], "rarity": "rare"},
{"id": "kakuzu", "name": "角都", "short": "角都", "icon": "角", "power": 102, "mult": 1.36, "elements": ["火", "风", "土"], "teams": ["晓"], "roles": ["强攻", "防守"], "tags": ["禁术"], "rarity": "epic"},
{"id": "zabuza", "name": "桃地再不斩", "short": "再不斩", "icon": "再", "power": 86, "mult": 1.26, "elements": ["水"], "teams": ["雾隐"], "roles": ["强攻", "控制"], "tags": ["忍刀", "水遁"], "rarity": "rare"},
{"id": "haku", "name": "白", "short": "白", "icon": "白", "power": 77, "mult": 1.24, "elements": ["水", "风"], "teams": ["雾隐"], "roles": ["控制", "支援"], "tags": ["冰遁"], "rarity": "rare"},
{"id": "mei", "name": "照美冥", "short": "照美冥", "icon": "照", "power": 99, "mult": 1.36, "elements": ["水", "火"], "teams": ["五影"], "roles": ["强攻", "控制"], "tags": ["熔遁", "水遁"], "rarity": "epic"},
{"id": "ay", "name": "四代雷影", "short": "雷影", "icon": "雷", "power": 108, "mult": 1.38, "elements": ["雷", "体"], "teams": ["五影", "云隐"], "roles": ["强攻", "防守"], "tags": ["雷铠"], "rarity": "epic"},
{"id": "bee", "name": "奇拉比", "short": "奇拉比", "icon": "奇", "power": 103, "mult": 1.38, "elements": ["雷", "体"], "teams": ["云隐"], "roles": ["强攻", "支援"], "tags": ["人柱力", "忍刀"], "rarity": "epic"},
{"id": "ohnoki", "name": "两天秤大野木", "short": "大野木", "icon": "大", "power": 103, "mult": 1.39, "elements": ["土", "风"], "teams": ["五影"], "roles": ["控制", "战术"], "tags": ["尘遁"], "rarity": "epic"},
{"id": "darui", "name": "达鲁伊", "short": "达鲁伊", "icon": "达", "power": 83, "mult": 1.25, "elements": ["水", "雷"], "teams": ["云隐"], "roles": ["强攻", "战术"], "tags": ["岚遁", "忍刀"], "rarity": "rare"},
{"id": "shisui", "name": "宇智波止水", "short": "止水", "icon": "止", "power": 99, "mult": 1.38, "elements": ["火", "风"], "teams": ["宇智波"], "roles": ["控制", "战术"], "tags": ["宇智波", "写轮眼", "幻术"], "rarity": "epic"},
{"id": "kabuto", "name": "药师兜", "short": "兜", "icon": "兜", "power": 88, "mult": 1.31, "elements": ["水", "阴"], "teams": ["音隐"], "roles": ["医疗", "战术"], "tags": ["医疗", "禁术", "仙人"], "rarity": "rare"},
{"id": "kimimaro", "name": "君麻吕", "short": "君麻吕", "icon": "君", "power": 89, "mult": 1.3, "elements": ["体", "土"], "teams": ["音隐"], "roles": ["强攻", "防守"], "tags": ["骨脉"], "rarity": "rare"},
{"id": "suigetsu", "name": "鬼灯水月", "short": "水月", "icon": "水", "power": 81, "mult": 1.25, "elements": ["水"], "teams": ["鹰小队"], "roles": ["强攻", "防守"], "tags": ["忍刀", "水遁"], "rarity": "rare"},
{"id": "karin", "name": "漩涡香燐", "short": "香燐", "icon": "香", "power": 64, "mult": 1.22, "elements": ["阴"], "teams": ["鹰小队", "漩涡家族"], "roles": ["医疗", "支援"], "tags": ["医疗", "封印"], "rarity": "uncommon"},
{"id": "jugo", "name": "重吾", "short": "重吾", "icon": "重", "power": 92, "mult": 1.29, "elements": ["土"], "teams": ["鹰小队"], "roles": ["强攻", "防守"], "tags": ["仙人", "咒印"], "rarity": "rare"},
{"id": "rin", "name": "野原琳", "short": "琳", "icon": "琳", "power": 61, "mult": 1.19, "elements": ["水"], "teams": ["水门班"], "roles": ["医疗", "支援"], "tags": ["医疗", "人柱力"], "rarity": "uncommon"},
{"id": "nagato", "name": "长门", "short": "长门", "icon": "长", "power": 119, "mult": 1.52, "elements": ["水", "阴"], "teams": ["晓"], "roles": ["控制", "战术"], "tags": ["轮回眼", "封印"], "rarity": "legendary"},
{"id": "kaguya", "name": "大筒木辉夜", "short": "辉夜", "icon": "辉", "power": 138, "mult": 1.65, "elements": ["火", "水", "阴"], "teams": ["大筒木"], "roles": ["强攻", "控制"], "tags": ["白眼", "时空间"], "rarity": "legendary"}
];

const RELICS = [
  {id:'shadow_scroll', name:'多重影分身之卷', icon:'影', rarity:'common', cost:7, text:'每张【强攻】牌使本次连锁倍率 ×1.28。'},
  {id:'chakra_thread', name:'查克拉丝线', icon:'丝', rarity:'common', cost:6, text:'首种以外，每多一种不同属性，基础伤害 +35%。'},
  {id:'medical_seal', name:'百豪储备', icon:'百', rarity:'uncommon', cost:9, text:'若含【医疗】，最终伤害 ×2.2；每战首次触发再 ×1.6。'},
  {id:'sharingan', name:'三勾玉写轮眼', icon:'写', rarity:'uncommon', cost:10, text:'每触发 1 个组合词条，连锁倍率额外 ×1.16。'},
  {id:'sage_mode', name:'仙人模式', icon:'仙', rarity:'rare', cost:12, text:'一次出击 4 张以上时，最终伤害 ×3。'},
  {id:'curse_mark', name:'咒印暴走', icon:'咒', rarity:'rare', cost:11, text:'恰好 3 张牌时 ×4.5；但本次出击后少抽 1 张。'},
  {id:'eight_gates', name:'八门遁甲', icon:'門', rarity:'rare', cost:13, text:'一次出击 5 张时 ×6；若含【八门遁甲】角色再 ×2。'},
  {id:'jinchuriki_core', name:'尾兽查克拉核', icon:'尾', rarity:'rare', cost:12, text:'每名【人柱力】使最终伤害 ×2.1。'},
  {id:'flying_raijin', name:'飞雷神术式', icon:'闪', rarity:'epic', cost:15, text:'选择顺序中每出现一次“雷→风”或“风→雷”，倍率 ×3.2。'},
  {id:'rinnegan', name:'轮回眼共鸣', icon:'輪', rarity:'epic', cost:17, text:'若本次触发 4 个以上组合，重演倍率链：组合总倍率再平方根式叠乘一次。'},
  {id:'edo_tensei', name:'秽土转生阵', icon:'禁', rarity:'epic', cost:16, text:'每战最后一次出击，本次每个宿命组合额外 ×1.8。'},
  {id:'wood_domain', name:'树界降诞', icon:'森', rarity:'epic', cost:16, text:'同时含【土】和【水】时 ×3.5；若含木遁角色再 ×2.5。'},
  {id:'akatsuki_ring', name:'晓之戒', icon:'晓', rarity:'epic', cost:15, text:'每名【晓】成员使倍率 ×1.85，3 名以上再 ×3。'},
  {id:'team_tactics', name:'小队战术卷轴', icon:'隊', rarity:'uncommon', cost:9, text:'同一小队达到 3 人时 ×3；达到 4 人时改为 ×7。'},
  {id:'element_prism', name:'五遁棱镜', icon:'遁', rarity:'legendary', cost:20, text:'每种不同属性使倍率 ×1.75；5 种属性时额外 ×10。'},
  {id:'destiny_knot', name:'宿命之结', icon:'結', rarity:'legendary', cost:21, text:'每个“宿命组合”倍率再 ×2.5。'},
  {id:'limit_break', name:'查克拉限界突破', icon:'∞', rarity:'legendary', cost:22, text:'单次伤害超过目标的 150% 时，全队威力永久 +4，每战一次。'},
  {id:'combo_engine', name:'连携演算式', icon:'Σ', rarity:'legendary', cost:24, text:'第 5 个及之后的组合词条，每个使最终伤害 ×2。'},
{"id": "ice_mirror", "name": "魔镜冰晶", "icon": "魔", "rarity": "rare", "cost": 12, "text": "含【冰遁】时 ×4；否则水与风共存时 ×2。"},
{"id": "puppet_core", "name": "百机赤秘", "icon": "百", "rarity": "rare", "cost": 12, "text": "每名【傀儡】角色 ×2.6；至少两人再 ×2。"},
{"id": "paper_wings", "name": "纸海天使", "icon": "纸", "rarity": "rare", "cost": 11, "text": "每名【支援】角色 ×1.7；含纸遁再 ×2。"},
{"id": "sword_archive", "name": "忍刀七卷", "icon": "忍", "rarity": "rare", "cost": 12, "text": "每名【忍刀】或【忍具】角色 ×1.9。"},
{"id": "crimson_chain", "name": "金刚封锁", "icon": "金", "rarity": "epic", "cost": 15, "text": "含【封印】时 ×3；含漩涡家族再 ×2。"},
{"id": "storm_drum", "name": "岚遁雷鼓", "icon": "岚", "rarity": "epic", "cost": 15, "text": "每段水→雷连携 ×2.8。"},
{"id": "hokage_cloak", "name": "历代火影御神袍", "icon": "历", "rarity": "epic", "cost": 16, "text": "每名【火影】角色 ×1.9，至少两人再 ×2。"},
{"id": "moon_mirror", "name": "月读之镜", "icon": "月", "rarity": "epic", "cost": 16, "text": "含【幻术】且有两名阴属性角色时 ×5。"},
{"id": "dust_cube", "name": "尘遁结晶", "icon": "尘", "rarity": "legendary", "cost": 20, "text": "含【尘遁】时 ×8；否则土风火共存时 ×3。"},
{"id": "sage_contract", "name": "仙兽契约", "icon": "仙", "rarity": "rare", "cost": 12, "text": "每名【通灵】或【仙人】角色 ×1.8。"},
{"id": "duet_bell", "name": "双人演武铃", "icon": "双", "rarity": "uncommon", "cost": 9, "text": "恰好两张牌时最终伤害 ×18。"},
{"id": "solo_kunai", "name": "孤影苦无", "icon": "孤", "rarity": "rare", "cost": 12, "text": "只出一张牌时最终伤害 ×80。"},
{"id": "echo_seal", "name": "回响封印", "icon": "回", "rarity": "epic", "cost": 15, "text": "与上次出击张数相同时 ×4；每战首次不触发。"},
{"id": "last_flame", "name": "不灭意志", "icon": "不", "rarity": "rare", "cost": 12, "text": "每战最后一次出击 ×8。"},
{"id": "chain_abacus", "name": "连锁算珠", "icon": "连", "rarity": "legendary", "cost": 22, "text": "每三个组合词条使最终伤害 ×3。"},
{"id": "war_banner", "name": "联军战旗", "icon": "联", "rarity": "epic", "cost": 16, "text": "至少四个不同小队共同行动时 ×6。"},
{"id": "treasure_frog", "name": "妙木宝囊", "icon": "妙", "rarity": "uncommon", "cost": 9, "text": "每战胜利额外获得 4 両。"},
{"id": "training_weights", "name": "青春负重", "icon": "青", "rarity": "uncommon", "cost": 10, "text": "每战胜利全队永久威力 +5。"}
];

const ENCOUNTERS = [
  {
    "chapter": 1,
    "chapterName": "波之国",
    "wave": 1,
    "name": "边境巡逻",
    "title": "远征遭遇",
    "target": 2800,
    "reward": 9,
    "mod": null
  },
  {
    "chapter": 1,
    "chapterName": "波之国",
    "wave": 2,
    "name": "大桥伏击",
    "title": "远征遭遇",
    "target": 4200,
    "reward": 9,
    "mod": null
  },
  {
    "chapter": 1,
    "chapterName": "波之国",
    "wave": 3,
    "name": "再不斩·无声暗杀",
    "title": "章节首领",
    "target": 6400,
    "reward": 13,
    "mod": "mist"
  },
  {
    "chapter": 2,
    "chapterName": "中忍试炼",
    "wave": 1,
    "name": "死亡森林",
    "title": "远征遭遇",
    "target": 9600,
    "reward": 10,
    "mod": null
  },
  {
    "chapter": 2,
    "chapterName": "中忍试炼",
    "wave": 2,
    "name": "预选对决",
    "title": "远征遭遇",
    "target": 14600,
    "reward": 10,
    "mod": null
  },
  {
    "chapter": 2,
    "chapterName": "中忍试炼",
    "wave": 3,
    "name": "大蛇丸·五行封印",
    "title": "章节首领",
    "target": 22000,
    "reward": 14,
    "mod": "seal"
  },
  {
    "chapter": 3,
    "chapterName": "木叶崩溃",
    "wave": 1,
    "name": "砂忍突袭",
    "title": "远征遭遇",
    "target": 33200,
    "reward": 11,
    "mod": null
  },
  {
    "chapter": 3,
    "chapterName": "木叶崩溃",
    "wave": 2,
    "name": "通灵兽攻城",
    "title": "远征遭遇",
    "target": 50100,
    "reward": 11,
    "mod": null
  },
  {
    "chapter": 3,
    "chapterName": "木叶崩溃",
    "wave": 3,
    "name": "我爱罗·砂之绝壁",
    "title": "章节首领",
    "target": 75700,
    "reward": 15,
    "mod": "armor"
  },
  {
    "chapter": 4,
    "chapterName": "追逐叛忍",
    "wave": 1,
    "name": "音忍结界",
    "title": "远征遭遇",
    "target": 114300,
    "reward": 12,
    "mod": null
  },
  {
    "chapter": 4,
    "chapterName": "追逐叛忍",
    "wave": 2,
    "name": "终末追击",
    "title": "远征遭遇",
    "target": 172600,
    "reward": 12,
    "mod": null
  },
  {
    "chapter": 4,
    "chapterName": "追逐叛忍",
    "wave": 3,
    "name": "君麻吕·骨林",
    "title": "章节首领",
    "target": 260600,
    "reward": 16,
    "mod": "thorns"
  },
  {
    "chapter": 5,
    "chapterName": "晓之猎影",
    "wave": 1,
    "name": "砂隐夺还",
    "title": "远征遭遇",
    "target": 393400,
    "reward": 13,
    "mod": null
  },
  {
    "chapter": 5,
    "chapterName": "晓之猎影",
    "wave": 2,
    "name": "百机操演",
    "title": "远征遭遇",
    "target": 594100,
    "reward": 13,
    "mod": null
  },
  {
    "chapter": 5,
    "chapterName": "晓之猎影",
    "wave": 3,
    "name": "赤砂之蝎·傀儡剧场",
    "title": "章节首领",
    "target": 897100,
    "reward": 17,
    "mod": "puppet"
  },
  {
    "chapter": 6,
    "chapterName": "不死之章",
    "wave": 1,
    "name": "飞段的仪式",
    "title": "远征遭遇",
    "target": 1354600,
    "reward": 14,
    "mod": null
  },
  {
    "chapter": 6,
    "chapterName": "不死之章",
    "wave": 2,
    "name": "角都的心脏",
    "title": "远征遭遇",
    "target": 2045500,
    "reward": 14,
    "mod": null
  },
  {
    "chapter": 6,
    "chapterName": "不死之章",
    "wave": 3,
    "name": "宇智波鼬·月读",
    "title": "章节首领",
    "target": 3088600,
    "reward": 18,
    "mod": "genjutsu"
  },
  {
    "chapter": 7,
    "chapterName": "佩恩来袭",
    "wave": 1,
    "name": "六道突袭",
    "title": "远征遭遇",
    "target": 4663800,
    "reward": 15,
    "mod": null
  },
  {
    "chapter": 7,
    "chapterName": "佩恩来袭",
    "wave": 2,
    "name": "地爆天星",
    "title": "远征遭遇",
    "target": 7042400,
    "reward": 15,
    "mod": null
  },
  {
    "chapter": 7,
    "chapterName": "佩恩来袭",
    "wave": 3,
    "name": "佩恩·查克拉黑洞",
    "title": "章节首领",
    "target": 10634000,
    "reward": 19,
    "mod": "drain"
  },
  {
    "chapter": 8,
    "chapterName": "五影集结",
    "wave": 1,
    "name": "雷影演武",
    "title": "远征遭遇",
    "target": 16057400,
    "reward": 16,
    "mod": null
  },
  {
    "chapter": 8,
    "chapterName": "五影集结",
    "wave": 2,
    "name": "雾隐风暴",
    "title": "远征遭遇",
    "target": 24246600,
    "reward": 16,
    "mod": null
  },
  {
    "chapter": 8,
    "chapterName": "五影集结",
    "wave": 3,
    "name": "带土·神威空间",
    "title": "章节首领",
    "target": 36612400,
    "reward": 20,
    "mod": "rift"
  },
  {
    "chapter": 9,
    "chapterName": "忍界大战",
    "wave": 1,
    "name": "白绝军团",
    "title": "远征遭遇",
    "target": 55284700,
    "reward": 17,
    "mod": null
  },
  {
    "chapter": 9,
    "chapterName": "忍界大战",
    "wave": 2,
    "name": "秽土联阵",
    "title": "远征遭遇",
    "target": 83479900,
    "reward": 17,
    "mod": null
  },
  {
    "chapter": 9,
    "chapterName": "忍界大战",
    "wave": 3,
    "name": "宇智波斑·神树根界",
    "title": "章节首领",
    "target": 126054600,
    "reward": 21,
    "mod": "roots"
  },
  {
    "chapter": 10,
    "chapterName": "月下终焉",
    "wave": 1,
    "name": "六道觉醒",
    "title": "远征遭遇",
    "target": 190342400,
    "reward": 18,
    "mod": null
  },
  {
    "chapter": 10,
    "chapterName": "月下终焉",
    "wave": 2,
    "name": "辉夜·天之御中",
    "title": "远征遭遇",
    "target": 287417100,
    "reward": 18,
    "mod": null
  },
  {
    "chapter": 10,
    "chapterName": "月下终焉",
    "wave": 3,
    "name": "终焉之谷·宿命双星",
    "title": "章节首领",
    "target": 433999800,
    "reward": 22,
    "mod": "finale"
  }
];

const BOSS_TEXT = {
  armor:'砂壁：不足三种属性时，伤害降低 65%。',
  thorns:'骨林：连续出击相同张数时，伤害降低 60%。',
  puppet:'傀儡：缺少战术角色时，伤害降低 55%。',
  rift:'神威：出击三张以上时，最后一张基础威力归零，组合仍生效。',
  mist:'雾隐：每次出击的第一张牌只提供 45% 基础威力。',
  seal:'封印：每次最多只能选择 4 张牌。',
  genjutsu:'幻术：每次出击随机封印一种属性，该属性卡牌威力减半。',
  drain:'吸收：本战基础倍率 -0.8，最低为 1。',
  roots:'根界：每次出击后锁住 1 张未选手牌，下一次不能选择。',
  finale:'终焉：目标极高，但每个宿命组合在本战额外 ×1.5。'
};

const STARTER_IDS = ['naruto','sasuke','sakura','kakashi','shikamaru','ino','choji','hinata','kiba','shino','gaara','temari','kankuro','lee','neji','sai'];

const COMBO_GLOSSARY = [
  ['第七班集结','鸣人 + 佐助 + 小樱（+卡卡西强化）'],
  ['猪鹿蝶','鹿丸 + 井野 + 丁次'],
  ['砂之三姐弟','我爱罗 + 手鞠 + 勘九郎'],
  ['传说三忍','自来也 + 纲手 + 大蛇丸'],
  ['凯班青春','凯 + 小李 + 宁次'],
  ['晓之共鸣','2 名以上晓成员'],
  ['宿命·双星','鸣人 + 佐助'],
  ['宿命·兄弟','佐助 + 鼬'],
  ['宿命·师徒','鸣人 + 自来也 / 水门'],
  ['宿命·终焉','柱间 + 斑'],
  ['属性连携','按选择顺序触发 风→火、水→雷、火→雷、雷↔风 等'],
  ['五遁大连弹','5 张牌凑齐 5 种不同属性']
];
